$key = "$env:USERPROFILE\.ssh\cryptooptiontool.pem"
$server = "root@8.216.43.113:/var/www/yayanews"
scp -o StrictHostKeyChecking=no -i $key "apps/web/src/dictionaries/zh.json" "$server/apps/web/src/dictionaries/"
scp -o StrictHostKeyChecking=no -i $key "apps/web/src/components/editorial/BreakingStreamBlock.tsx" "$server/apps/web/src/components/editorial/"
scp -o StrictHostKeyChecking=no -i $key "apps/web/src/components/ArticleCard.tsx" "$server/apps/web/src/components/"
scp -o StrictHostKeyChecking=no -i $key "apps/web/src/lib/article-image.ts" "$server/apps/web/src/lib/"
scp -o StrictHostKeyChecking=no -i $key "apps/web/src/lib/queries.ts" "$server/apps/web/src/lib/"
scp -o StrictHostKeyChecking=no -i $key "apps/web/public/images/article-placeholder-en.svg" "$server/apps/web/public/images/"
scp -o StrictHostKeyChecking=no -i $key "apps/web/public/db1162aa32014bba89ab29ba04a5ddba.txt" "$server/apps/web/public/"
ssh -o StrictHostKeyChecking=no -i $key root@8.216.43.113 "mkdir -p /var/www/yayanews/apps/web/src/app/api/webhooks/indexing /var/www/yayanews/apps/web/src/app/feed-news.xml"
scp -o StrictHostKeyChecking=no -i $key "apps/web/src/app/api/webhooks/indexing/route.ts" "$server/apps/web/src/app/api/webhooks/indexing/"
scp -o StrictHostKeyChecking=no -i $key "apps/web/src/app/sitemap-news.xml/route.ts" "$server/apps/web/src/app/sitemap-news.xml/"
scp -o StrictHostKeyChecking=no -i $key "apps/web/src/app/feed-news.xml/route.ts" "$server/apps/web/src/app/feed-news.xml/"
scp -o StrictHostKeyChecking=no -i $key "apps/web/src/app/robots.ts" "$server/apps/web/src/app/"
scp -o StrictHostKeyChecking=no -i $key "apps/pipeline/pipeline/utils/indexer.py" "$server/apps/pipeline/pipeline/utils/"
scp -o StrictHostKeyChecking=no -i $key "apps/pipeline/pipeline/utils/database.py" "$server/apps/pipeline/pipeline/utils/"
scp -o StrictHostKeyChecking=no -i $key "infra/scripts/push-all-to-google.ts" "$server/infra/scripts/"
ssh -o StrictHostKeyChecking=no -i $key root@8.216.43.113 "cd /var/www/yayanews && npm ci && npm run build --workspace=@yayanews/web && node infra/scripts/copy-standalone.mjs && pm2 reload yayanews && pm2 restart pipeline"
